version: '3.7'
services:
  front:
    container_name: front
    image: node:10.15.1
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    tty: true
    command: bash -c "npm install -g yarn && yarn install && yarn dev"
    ports:
      - '5000:5000'
    environment:
      - HOST=0.0.0.0
    ports:
      - 5002:3000